# The config file for rboot.

# The virtual address offset from which physical memory is mapped, as described in
# https://os.phil-opp.com/paging-implementation/#map-the-complete-physical-memory
physical_memory_offset=0xFFFF800000000000

# The address at which the kernel stack is placed.
kernel_stack_addr=0xFFFFFF0100000000

# The size of the kernel stack, given in number of 4KiB pages. Defaults to 512.
kernel_stack_size=1048576

# The max address for kernel stack
kernel_stack_max=0xFFFFFF0200000000

# The default number of pages that a initial kernel stack contain
kernel_default_page=8

# Define if the kernel stack will auto grow (handled by kernel).
# Defaults to 0, meaning no. If greater than 0, the bootloader will only alloc specified number of 4KiB pages.
kernel_stack_auto_grow=8

<<<<<<< HEAD:src/0x02/crates/kernel/config/boot.conf
# Set the kernel log level: Normal, Debug, Verbose
log_level=Normal
=======
# The path of kernel ELF
kernel_path=\KERNEL.ELF

# The max address for stack
stack_max_addr=0x400000000000

# The max number of pages that stack can contain
stack_max_pages=0x100000

# The default number of pages that a initial stack contain
stack_default_page=1

# Set the kernel log level: Normal, Debug, Verbose
log_level=Debug

# Load APP
load_apps=0

>>>>>>> dev/lab3:src/0x03/crates/kernel/config/boot.conf
